CREATE TABLE IF NOT EXISTS hourly_usage(
    hour TIMESTAMP PRIMARY KEY,
    community_produced DOUBLE PRECISION NOT NULL DEFAULT 0,
    community_used DOUBLE PRECISION NOT NULL DEFAULT 0,
    grid_used DOUBLE PRECISION NOT NULL DEFAULT 0
)
